##### Import libraries

In [1]:
import numpy as np

from sklearn.linear_model import LinearRegression   # Machine learning library

import tensorflow as tf                             # Deep learning library
print(f'Tensorflow version: {tf.__version__}')

# Visualization library
import matplotlib.pyplot as plt
import imageio

2023-08-10 11:26:07.585490: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


Tensorflow version: 2.12.0


##### Shared data

In [2]:
train_x = np.array([[5], [-10], [9], [0], [4], [2]])
train_y = np.array([17, -28, 29, 2, 14, 8])         # train_y = train_x * 3 + 2

##### with Machine Learning(Linear Regression)

In [3]:
lr_model = LinearRegression()
lr_model.fit(train_x, train_y)

LinearRegression()

In [4]:
lr_predictions = lr_model.predict(train_x)

In [5]:
lr_predictions = lr_model.predict(train_x)
for i in range(len(train_x)):
    print(
        f'Input data: {train_x[i][0]:3d}, '
        f'Label data: {train_y[i]:3d}, '
        f'Prediction data: {lr_predictions[i]:8.5f}'
    )

Input data:   5, Label data:  17, Prediction data: 17.00000
Input data: -10, Label data: -28, Prediction data: -28.00000
Input data:   9, Label data:  29, Prediction data: 29.00000
Input data:   0, Label data:   2, Prediction data:  2.00000
Input data:   4, Label data:  14, Prediction data: 14.00000
Input data:   2, Label data:   8, Prediction data:  8.00000


In [6]:
# Prediction
# train_x = 1 --> train_y = 1 * 3 + 2 = 5
lr_predictions = lr_model.predict([[1]])
lr_predictions

array([5.])

##### with Simple Deep Learning

In [7]:
# Model construction
dl_model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=1, input_shape=(1,))
])

# Model compile and learning
dl_model.compile(
    optimizer='adam',
    loss='mean_squared_error'
)

# epochs를 1000번 할 때까지는 정확도가 좋지 않았음
dl_model.fit(train_x, train_y, epochs=10000, verbose=0)

2023-08-10 11:26:16.252607: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1635] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 22787 MB memory:  -> device: 0, name: NVIDIA TITAN RTX, pci bus id: 0000:5e:00.0, compute capability: 7.5
2023-08-10 11:26:16.253865: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1635] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 22265 MB memory:  -> device: 1, name: NVIDIA TITAN RTX, pci bus id: 0000:af:00.0, compute capability: 7.5
2023-08-10 11:26:18.455516: I tensorflow/compiler/xla/service/service.cc:169] XLA service 0x2c3d49b0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2023-08-10 11:26:18.455588: I tensorflow/compiler/xla/service/service.cc:177]   StreamExecutor device (0): NVIDIA TITAN RTX, Compute Capability 7.5
2023-08-10 11:26:18.455612: I tensorflow/compiler/xla/service/service.cc:177]   StreamExecutor device (1): NVIDIA TITAN RTX, Compute Capability 7.5
202

In [8]:
# Prediction
# train_x = 1 --> train_y = 1 * 3 + 2 = 5
dl_predictions = dl_model.predict([[1]], verbose=0)
dl_predictions

array([[5.000017]], dtype=float32)

In [9]:
dl_predictions = dl_model.predict(train_x, verbose=0)

for i in range(len(train_x)):
    print(
        f'Input data: {train_x[i][0]:3d}, '
        f'Label data: {train_y[i]:3d}, '
        f'Prediction data: {dl_predictions[i][0]:8.5f}'
    )

Input data:   5, Label data:  17, Prediction data: 16.99999
Input data: -10, Label data: -28, Prediction data: -27.99990
Input data:   9, Label data:  29, Prediction data: 28.99995
Input data:   0, Label data:   2, Prediction data:  2.00003
Input data:   4, Label data:  14, Prediction data: 13.99999
Input data:   2, Label data:   8, Prediction data:  8.00001


##### with Deep Learning

In [10]:
dl2_model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=64, activation='relu', input_shape=(1,)),
    tf.keras.layers.Dense(units=32, activation='relu'),
    tf.keras.layers.Dense(units=1)
])

dl2_model.compile(
    optimizer='adam',
    loss='mean_squared_error'
)

In [11]:
dl2_model.fit(train_x, train_y, epochs=1000, verbose=0)

In [12]:
# Prediction
# train_x = 1 --> train_y = 1 * 3 + 2 = 5
dl2_predictions = dl2_model.predict([[1]], verbose=0)
dl2_predictions

array([[5.047438]], dtype=float32)

In [13]:
dl2_predictions = dl2_model.predict(train_x, verbose=0)

for i in range(len(train_x)):
    print(
        f'Input data: {train_x[i][0]:3d}, '
        f'Label data: {train_y[i]:3d}, '
        f'Prediction data: {dl2_predictions[i][0]:8.5f}'
    )

Input data:   5, Label data:  17, Prediction data: 17.01116
Input data: -10, Label data: -28, Prediction data: -27.99944
Input data:   9, Label data:  29, Prediction data: 28.97476
Input data:   0, Label data:   2, Prediction data:  1.97534
Input data:   4, Label data:  14, Prediction data: 14.02022
Input data:   2, Label data:   8, Prediction data:  8.03837


##### with Deep Learning (Visualization)

In [14]:
vdl_model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=64, activation='relu', input_shape=(1,)),
    tf.keras.layers.Dense(units=32, activation='relu'),
    tf.keras.layers.Dense(units=1)
])

vdl_model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['accuracy']
)

weights_history = []
for epoch in range(1001):
    vdl_model.fit(train_x, train_y, epochs=1, verbose=0)
    weights = vdl_model.get_weights()
    weights_history.append(weights)
    if epoch % 100 == 0:
        print(
            f'Epoch: {epoch:04d}, '
            f'Loss: {vdl_model.history.history["loss"]}, '
            f'Accuracy: {vdl_model.history.history["accuracy"]}'
        )

Epoch: 0000, Loss: [364.8260498046875], Accuracy: [0.0]
Epoch: 0100, Loss: [81.30591583251953], Accuracy: [0.0]
Epoch: 0200, Loss: [0.2001866102218628], Accuracy: [0.0]
Epoch: 0300, Loss: [0.04334158077836037], Accuracy: [0.0]
Epoch: 0400, Loss: [0.017622241750359535], Accuracy: [0.0]
Epoch: 0500, Loss: [0.007116349413990974], Accuracy: [0.0]
Epoch: 0600, Loss: [0.0027655765879899263], Accuracy: [0.0]
Epoch: 0700, Loss: [0.001132157165557146], Accuracy: [0.0]
Epoch: 0800, Loss: [0.0005624322802759707], Accuracy: [0.0]
Epoch: 0900, Loss: [0.00035976027720607817], Accuracy: [0.0]
Epoch: 1000, Loss: [0.0002693807182367891], Accuracy: [0.0]


* Generation GIF Images
  * `11-BASIC-T212P38/61_animation_gif.ipynb` 참조