In [1]:
import os
import numpy as np
import pandas as pd
import tensorflow as tf

2023-09-02 10:07:04.710086: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
_PATH_BASE = os.path.join(os.getcwd(), 'data')
df_daily = pd.read_csv(
    os.path.join(_PATH_BASE, 'b_daily.csv'), 
    index_col=None
)

df_daily.drop('index', axis=1, inplace=True)

In [3]:
WINDOW_SIZE = 7
target_col = 'ACTIVE_POWER_sum'
column_indices = {name: i for i, name in enumerate(df_daily.columns)}
target_idx = column_indices[target_col]

In [4]:
# Features, Target 분류
X_data_win = []
y_data_win = []
nd_daily = df_daily.values

for _i in range(df_daily.shape[0] - WINDOW_SIZE):
    X_data_win.append(nd_daily[_i:_i+WINDOW_SIZE, :])
    y_data_win.append(nd_daily[_i+WINDOW_SIZE, target_idx])

X_data_win = np.array(X_data_win)
y_data_win = np.array(y_data_win)

In [5]:
np.save(os.path.join(_PATH_BASE, 'b_daily_feature.npy'), X_data_win)
np.save(os.path.join(_PATH_BASE, 'b_daily_label.npy'), y_data_win)

In [ ]:
def make_window(data, window_size, batch_size, shuffle):
    ds = tf.data.Dataset.from_tensor_slices(data)
    ds = ds.window(window_size+1, shift=1, drop_remainder=True)
    

In [6]:
ds = tf.data.Dataset.from_tensor_slices(nd_daily)

2023-09-02 10:07:05.963818: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-09-02 10:07:05.967777: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-09-02 10:07:05.967917: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

In [13]:
ds = ds.window(size=WINDOW_SIZE, shift=1, stride=1, drop_remainder=True)

In [14]:
ds

<_WindowDataset element_spec=DatasetSpec(DatasetSpec(DatasetSpec(TensorSpec(shape=(17,), dtype=tf.float64, name=None), TensorShape([])), TensorShape([])), TensorShape([]))>

In [10]:
132*7

924

In [16]:
temp_ndarray = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [30]:
def test_func(x):
    print(x)
    tf.print(x)
    return tf.data.Dataset.from_tensor_slices(x)

In [31]:
temp_ds = test_func(temp_ndarray)
list(temp_ds.as_numpy_iterator())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [32]:
temp_ds2 = temp_ds.flat_map(test_func)
list(temp_ds2.as_numpy_iterator())

Tensor("args_0:0", shape=(3,), dtype=int64)
[1 2 3]
[4 5 6]
[7 8 9]


[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
tf.print(temp_ds)

<_TensorSliceDataset element_spec=TensorSpec(shape=(3,), dtype=tf.int64, name=None)>
